# # Configuration options for dependency updates
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for maven
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '10:00'
      timezone: 'Asia/Shanghai'
    reviewers:
      - 'Runrioter'
    labels:
      - 'dependencies'
